class Screens(dict):

    def return_screens(screen):

        # Data Dictionary of screens
        screens={
            'dashboard': '/mainDash/dashboard',
            'account_overview': '/biAccount/overview',
            'account_positions': '/biAccount/positions',
            'account_balances': '/biAccount/balances',
            'account_activity': '/biAccount/activities',
            'account_cashflow': '/biAccount/cashFlow',
            'account_ira': '/biAccount/ira',
            'account_commissions': '/biAccount/commissions',
            'account_account_info': '/biAccount/accountInfo',
            'account_order_inquiry': '/biAccount/orderInquiry',
            'account_maturing_securities': '/biAccount/maturingSecurities',
            'account_funds_distribution': '/biAccount/fundsDistribution',
            'gains_loss_holdings': '/biGainLoss/holdings',
            'gains_tax_info': '/biGainLoss/taxInfo',
            'gains_projected_income': '/biGainLoss/projectedIncome',
            'gains_pending_income': '/biGainLoss/pendingIncome',
            'gains_reinvested_div': '/biGainLoss/reinvestedDiv',
            'order_entry_equities_options': 'biOrderEntry/equitiesBI',
            'order_entry_mutual_funds': 'biOrderEntry/mutualFunds',
            'order_entry_bonds': 'biOrderEntry/bonds',
            'order_entry_uit': 'biOrderEntry/uit',
            'order_entry_order_billing': 'biOrderEntry/orderBilling',
            'order_entry_pips': 'biOrderEntry/pips',
            'housekeeping_documents': 'biHousekeeping/documents',
            'housekeeping_shareholder_materials': 'biHousekeeping/shareholderMaterials',
            'housekeeping_activity': 'biHousekeeping/activity',
            'housekeeping_action_items': 'biHousekeeping/actionItems',
            'housekeeping_open_orders': 'biHousekeeping/openOrders',
            'housekeeping_open_details': 'biHousekeeping/orderDetails',
            'housekeeping_ACAT_status': 'biHousekeeping/acatStatus',
            'housekeeping_reorg_tracking': 'biHousekeeping/reorgTracking',
            'housekeeping_maturity_schedule': 'biHousekeeping/maturitySchedule',
            'housekeeping_new_account': 'biHousekeeping/newAccount',
            'housekeeping_account_transfer': 'biHousekeeping/accountTransfer',
            'housekeeping_update_account_transfer': 'biHousekeeping/updateAccount',
            'housekeeping_mf_questionnaire': 'biHousekeeping/mfQuestionnaire',
            'housekeeping_mf_questionnaire_MGR': 'biHousekeeping/mfQuestionnaireMgr',
            'performance_commissions': 'biPerformance/commissions',
            'performance_analysis': 'biPerformance/analysis',
            'performance_branch': 'biPerformance/branch',
            'tools_client_search': '/biTools/clientSearch',
            'tools_stock_record': '/biTools/stockRecord',
            'tools_ACATS': '/biTools/ACATS',
            'tools_bond_rating': '/biTools/bondRatings',
            'tools_folio_dx': '/biTools/folioDx',
            'tools_calculators': '/bitools/calculators',
            'tools_research': '/bitools/research',
            'tools_wedbush_research': '/bitools/wedbushResearch',
            'tools_firelight': '/bitools/fireLight',
            'logout': 'user/login?logout=1'
            }
        return screens[screen]